---
application:
  name: "dogefiles-server"
  project: "dogefiles-server"
  organization: "QoveryCommunity"
routers:
- name: "main-dogefiles-server"
  routes:
  - application_name: "dogefiles-server"
    paths:
    - "/*"
